name: manage-azure-policy-d6c83a60
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Audit_Linux_PowerShell_file_permission_policy_9a266df9-9049-49fd-9189-d6ad0df2a979/**'
#      - .github/workflows/manage-azure-policy-d6c83a60.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d6c83a60}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Audit_Linux_PowerShell_file_permission_policy_9a266df9-9049-49fd-9189-d6ad0df2a979/**
