name: manage-azure-policy-6c2882c6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/AINE_Policies_for_E2E_Tests_-_PROD_a1633742-69fb-445d-ad74-5cac2bb29a4e/**'
#      - .github/workflows/manage-azure-policy-6c2882c6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_6c2882c6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/AINE_Policies_for_E2E_Tests_-_PROD_a1633742-69fb-445d-ad74-5cac2bb29a4e/**
