name: manage-azure-policy-e731bcd7
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/_DONOT_DELETE_E2E_daily_MA_test_initiative_f1a6e6ab357a4d359db6f0f3/**'
#      - .github/workflows/manage-azure-policy-e731bcd7.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e731bcd7}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/_DONOT_DELETE_E2E_daily_MA_test_initiative_f1a6e6ab357a4d359db6f0f3/**
